# Generated by Django 5.2 on 2025-04-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Img", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Img", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N_season", models.IntegerField()),
                ("ReleaseDate", models.DateField(blank=True, null=True)),
                ("Nb_episode", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=300)),
                ("Genre", models.JSONField(blank=True, default=list, null=True)),
                ("Imdb", models.FloatField(max_length=12)),
                ("Trailer", models.URLField(blank=True, null=True)),
                ("Poster", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("documentary", "Documentary"),
                            ("kids", "Kids"),
                            ("series", "Series"),
                            ("anime", "Anime"),
                            ("short", "Short Film"),
                        ],
                        default="movie",
                        max_length=20,
                    ),
                ),
                ("Video", models.URLField(blank=True, null=True)),
                ("Duration", models.IntegerField()),
                ("ReleaseDate", models.DateField()),
                ("Actors", models.ManyToManyField(blank=True, to="videos.actor")),
                (
                    "Director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.director",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nb_episode", models.IntegerField()),
                ("Video", models.URLField(blank=True, null=True)),
                (
                    "Season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.season"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=300)),
                ("Genre", models.JSONField(blank=True, default=list, null=True)),
                ("Imdb", models.FloatField(max_length=12)),
                ("Trailer", models.URLField(blank=True, null=True)),
                ("Poster", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("documentary", "Documentary"),
                            ("kids", "Kids"),
                            ("series", "Series"),
                            ("anime", "Anime"),
                            ("short", "Short Film"),
                        ],
                        default="series",
                        max_length=20,
                    ),
                ),
                ("Nb_season", models.IntegerField()),
                ("Actors", models.ManyToManyField(blank=True, to="videos.actor")),
                (
                    "Director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.director",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="season",
            name="Serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.serie"
            ),
        ),
    ]
