# Generated by Django 5.2 on 2025-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="type",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("documentary", "Documentary"),
                    ("kids", "Kids"),
                    ("series", "Series"),
                    ("anime", "Anime"),
                    ("short", "Short Film"),
                    ("tv_show", "TV Show"),
                ],
                default="movie",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="serie",
            name="type",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("documentary", "Documentary"),
                    ("kids", "Kids"),
                    ("series", "Series"),
                    ("anime", "Anime"),
                    ("short", "Short Film"),
                    ("tv_show", "TV Show"),
                ],
                default="series",
                max_length=20,
            ),
        ),
    ]
