# Generated by Django 5.2 on 2025-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_film_type_alter_serie_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="category",
            field=models.CharField(
                choices=[
                    ("popular", "Popular"),
                    ("fantasy", "Fantasy"),
                    ("action", "Action"),
                    ("thriller", "Thriller"),
                    ("new_releases", "New Releases"),
                    ("just_for_you", "Just For You"),
                    ("trending_now", "Trending Now"),
                ],
                default="popular",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serie",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
