# Generated by Django 5.2 on 2025-04-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_film_category_film_is_popular_serie_is_popular"),
    ]

    operations = [
        migrations.AddField(
            model_name="serie",
            name="category",
            field=models.CharField(
                choices=[
                    ("popular", "Popular"),
                    ("fantasy", "Fantasy"),
                    ("action", "Action"),
                    ("thriller", "Thriller"),
                    ("new_releases", "New Releases"),
                    ("just_for_you", "Just For You"),
                    ("trending_now", "Trending Now"),
                ],
                default="popular",
                max_length=50,
            ),
        ),
    ]
