# Generated by Django 5.2 on 2025-05-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                            ("4K", "4K"),
                        ],
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualities",
                        to="videos.film",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Video Qualities",
                "unique_together": {("film", "quality")},
            },
        ),
    ]
