# Generated by Django 5.2 on 2025-05-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="serie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serie_reviews",
                to="videos.serie",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="film",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="film_reviews",
                to="videos.film",
            ),
        ),
    ]
