# Generated by Django 5.2 on 2025-05-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_review_serie_alter_review_film"),
        ("videos", "0007_videoquality"),
    ]

    operations = []
