# Generated by Django 5.2 on 2025-04-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="Actors",
        ),
        migrations.RemoveField(
            model_name="serie",
            name="Actors",
        ),
        migrations.RemoveField(
            model_name="film",
            name="Director",
        ),
        migrations.RemoveField(
            model_name="serie",
            name="Director",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="Season",
        ),
        migrations.RemoveField(
            model_name="season",
            name="Serie",
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.DeleteModel(
            name="Film",
        ),
        migrations.DeleteModel(
            name="Director",
        ),
        migrations.DeleteModel(
            name="Episode",
        ),
        migrations.DeleteModel(
            name="Season",
        ),
        migrations.DeleteModel(
            name="Serie",
        ),
    ]
